---

- name: Install all needed packages (Ubuntu Trusty)
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - nginx
    - php5-fpm
  when: ansible_distribution_release == "trusty"

- name: Set facts Ubuntu Trusty
  set_fact:
    misp_fast_cgi_pass: "unix:/var/run/php5-fpm.sock"
  when: ansible_distribution_release == "trusty"


