---

- name: Install all needed packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    install_recommends: no
  with_items:
    - gcc
    - zip
    - php-pear
    - git
    - redis-server
    - make
    - libxml2-dev
    - sudo
    - libxslt1-dev
    - zlib1g-dev
    - curl
    - gnupg-agent
    - php7.0
    - php7.0-cli
    - php7.0-dev
    - php7.0-json
    - php7.0-xml
    - php7.0-mysql
    - php7.0-readline
    - php-redis
    - php7.0-mbstring
    - php-pear
    - python3-dev
    - python3-pip
    - python3-setuptools
